/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anton Perfilev (https://sketchfab.com/wintermute666)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/provocative-pink-shoes-b230d90d71854d858711fc0a68749327
Title: "Provocative Pink" Shoes
*/

import React, { useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import Shoes from './provocative_pink_shoes.glb'
import { a } from '@react-spring/three'

const Shoe = (props) => {
  const shoeRef = useRef();
  const { nodes, materials } = useGLTF(Shoes);

  useFrame(() => {
    if (shoeRef.current) {
      shoeRef.current.rotation.y += 0.001;
    }
  });

  return (
    <a.group ref={shoeRef} {...props}>
      <mesh
        geometry={nodes.Plane050__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[33.331, 53.719, 65.551]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </a.group>
  );
}

export default Shoe;